# GitHub action to deploy quiz api to azure

name: Deploy Quiz API 

on: 
  workflow_dispatch: # Allows manual triggering
  push: # Trigger on pushes to main branch
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Ensure your project uses this version

      - name: Install dependencies
        run: dotnet restore ./QuizAPI.sln

      - name: Build
        run: dotnet build ./QuizAPI/QuizAPI.csproj --configuration Release --no-restore