# GitHub Action to deploy Quiz API to Azure App Service

name: Deploy Quiz API 

on: 
  # Trigger deployment on push to the master branch
  push:
    branches:
      - master
  # Allow manual triggering of the workflow
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: "datastructviz-quiz-api-001"

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup .NET Core
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ./QuizAPI.sln

      # Step 4: Build the project
      - name: Build
        run: dotnet build ./QuizAPI/QuizAPI.csproj --configuration Release --no-restore

      # Step 5: Publish the project
      - name: Publish
        run: dotnet publish ./QuizAPI/QuizAPI.csproj --configuration Release --output ./publish --no-restore

      # Step 6: Deploy to Azure
      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish


